export const FETCH_TICKET_OFFICE_LIST = 'FETCH_TICKET_OFFICE_LIST';
export const BOOK_TICKET = 'BOOK_TICKET';
export const BOOK_TICKET_SUCCESS = 'BOOK_TICKET_SUCCESS';
export const SWITCH_TAB = 'SWITCH_TAB';